PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "bids" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "property_id" integer(11) NOT NULL, "bid_date" datetime, "staging_fee" decimal(5,2), "distribution_fee" decimal(5,2), "rental_weekly" decimal(5,2), "rental_monthly" decimal(5,2), "rental" decimal(5,2), "weeks_included" integer(4), "complimentary_weeks" integer(4), "discount_percent" integer(4) DEFAULT 0, "discount_amount" decimal(5,2) DEFAULT 0.0 );
INSERT INTO "bids" VALUES(40,44,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(41,45,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(42,46,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(43,44,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(44,44,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(45,44,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(46,47,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(47,48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(48,44,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(49,49,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(50,50,NULL,1500,300,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO "bids" VALUES(51,51,NULL,1525,300,NULL,NULL,NULL,NULL,NULL,0,0);
CREATE INDEX "bids_bids_uidx1" ON "bids" ("property_id", "bid_date");
CREATE INDEX "bids_bids_idx1" ON "bids" ("property_id");
COMMIT;

